In [37]:
import pandas as pd

df=pd.read_csv("210809자료합친파일.csv")
df.set_index('국가', inplace=True)
df

,2018;국내총생산(GDP $),2019;국내총생산(GDP $),합계출산;2015,합계출산;2020,도시화율;2020,평균교육기간(년);2018,1인당 GNI(구매력환산기준 2011) (달러);2018,2020;연간 인구증가율,2020;0~14세 인구 구성비,2020;15~64세 인구 구성비,2020;65세이상 인구 구성비
국가,,,,,,,,,,,
아프가니스탄,18353881129.525 (US$),19291104007.614 (US$),5.45,4.56,26.0,3.9,"1,746",2.304 (annual %),41.823 (% of total),55.528 (% of total),2.649 (% of total)
알바니아,15147020535.387 (US$),15286612572.690 (US$),1.71,1.62,62.1,10.1,"12,300",-0.578 (annual %),17.236 (% of total),68.060 (% of total),14.705 (% of total)
알제리,175414987760.927 (US$),171157803367.473 (US$),2.96,3.05,73.7,8.0,"13,639",1.837 (annual %),30.784 (% of total),62.474 (% of total),6.743 (% of total)
미국령사모아,641000000.000 (US$),638000000.000 (US$),NaN,NaN,NaN,NaN,NaN,-0.208 (annual %),NaN,NaN,NaN
안도라,3218316013.226 (US$),3155065487.518 (US$),NaN,NaN,87.9,10.2,"48,641",0.154 (annual %),NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
에리트레아,NaN,NaN,4.35,4.10,41.3,3.9,"1,708",NaN,NaN,NaN,NaN
오세아니아,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
유럽,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
지브롤터,NaN,NaN,NaN,NaN,100.0,NaN,NaN,-0.045 (annual %),NaN,NaN,NaN
프랑스령폴리네시아,NaN,NaN,2.04,1.95,NaN,NaN,NaN,0.578 (annual %),22.223 (% of total),68.708 (% of total),9.068 (% of total)

In [39]:
df[['합계출산;2020','평균교육기간(년);2018']].corr()
df[['합계출산;2020','평균교육기간(년);2018']]

           합계출산;2020  평균교육기간(년);2018
국가
아프가니스탄          4.56             3.9
알바니아            1.62            10.1
알제리             3.05             8.0
미국령사모아           NaN             NaN
안도라              NaN            10.2
...              ...             ...
에리트레아           4.10             3.9
오세아니아            NaN             NaN
유럽               NaN             NaN
지브롤터             NaN             NaN
프랑스령폴리네시아       1.95             NaN

[229 rows x 2 columns]

In [40]:
df[['합계출산;2020','2019;국내총생산(GDP $)']].dropna()
df[['합계출산;2020','2018;국내총생산(GDP $)']].dropna()

           합계출산;2020         2018;국내총생산(GDP $)
국가
아프가니스탄          4.56     18353881129.525 (US$)
알바니아            1.62     15147020535.387 (US$)
알제리             3.05    175414987760.927 (US$)
앙골라             5.55    101353230784.594 (US$)
앤티가바부다          2.00      1605351851.852 (US$)
...              ...                       ...
짐바브웨            3.63     19523622341.613 (US$)
몬테네그로           1.75      5506767831.838 (US$)
세르비아            1.46     50640650221.462 (US$)
미국령버진아일랜드       2.05      3984000000.000 (US$)
세계              2.47  86347154919771.900 (US$)

[183 rows x 2 columns]

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 229 entries, 아프가니스탄 to 프랑스령폴리네시아
Data columns (total 11 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   2018;국내총생산(GDP $)                203 non-null    object
 1   2019;국내총생산(GDP $)                197 non-null    object
 2   합계출산;2015                        195 non-null    float64
 3   합계출산;2020                        195 non-null    float64
 4   도시화율;2020                        200 non-null    float64
 5   평균교육기간(년);2018                   188 non-null    float64
 6   1인당 GNI(구매력환산기준 2011) (달러);2018  190 non-null    object
 7   2020;연간 인구증가율                    210 non-null    object
 8   2020;0~14세 인구 구성비                191 non-null    object
 9   2020;15~64세 인구 구성비               191 non-null    object
 10  2020;65세이상 인구 구성비                191 non-null    object
dtypes: float64(4), object(7)
memory usage: 21.5+ KB